### ISSUE TITLE
6.1.0 - Errors when ExperimentalWarning is caught

### ISSUE THREAD

**Issue by abrenneke** [ehmicky/log-process-errors#32]
**Describe the bug**

Error in 6.1.0 when an ExperimentalWarning is caught:

```
TypeError: Cannot read property 'stack' of undefined
    at message (node_modules/log-process-errors/src/error/stack.js:4:37)
    at getError (node_modules/log-process-errors/src/error/main.js:16:36)
    at logEvent (node_modules/log-process-errors/src/handle/common.js:42:39)
    at handleEvent (node_modules/log-process-errors/src/handle/common.js:36:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Steps to reproduce**

Have this module process an ExperimentalWarning (maybe others). In my case it was:

```
ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (internal/util.js:183:11)
    at resolveExportsTarget (internal/modules/cjs/loader.js:607:13)
    at applyExports (internal/modules/cjs/loader.js:500:14)
    at resolveExports (internal/modules/cjs/loader.js:549:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:664:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Object._resolveFilename (/node_modules/rewiremock/lib/module.js:60:32)
    at /node_modules/rewiremock/lib/executor.js:269:29
    at tryOr (/node_modules/rewiremock/lib/executor.js:224:12)
    at Function.mockLoader (/node_modules/rewiremock/lib/executor.js:268:21) {
  name: 'ExperimentalWarning'
}
```

Don't have time for additional info right at this moment, sorry!

**Comment by ehmicky** [comment]
Hi @abrenneke,

Thanks for reporting this bug!

This should be fixed in [`6.1.1`](https://github.com/ehmicky/log-process-errors/releases/tag/6.1.1).

By curiosity, could you please copy/paste the output of the following command?

```
npx envinfo --system --binaries --browsers --npmPackages log-process-errors
```

**Comment by abrenneke** [comment]
Sure @ehmicky 

```
npx: installed 1 in 1.242s

  System:
    OS: Linux 4.13 CentOS Linux 7 (Core)
    CPU: (6) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 480.59 MB / 7.79 GB
    Container: Yes
    Shell: 5.0.2 - /bin/zsh
  Binaries:
    Node: 13.9.0 - ~/.nvm/versions/node/v13.9.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.9.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.80
  npmPackages:
    log-process-errors: 6.1.0 => 6.1.0
```

My log-process-errors call is like this:

```javascript
const ignoreWarnings = [
    // Ignore warnings about experimental features
    /queueMicrotask\(\) is experimental/,
    /Conditional exports is an experimental feature/
];

logProcessErrors({
    level: {
        warning: error => ( ignoreWarnings.some( r => r.test( error?.message ) ) ? 'silent' : 'default' ),

        // Disabled for now
        multipleResolves: constant( 'silent' )
    }
});
```

**Comment by ehmicky** [comment]
Thanks for the follow-up! 
Please let me know if you've got any other issue :+1:
